workflows:
  android-workflow:
    name: Android Workflow
    environment:
      groups:
        - google_play
        - keystore_credentials 
      vars:
        PACKAGE_NAME: $PACKAGE_NAME
        GOOGLE_PLAY_TRACK: $GOOGLE_PLAY_TRACK
    android_signing:
      - keystore_path: /tmp/keystore.jks
        keystore_password: $CM_KEYSTORE_PASSWORD
        key_alias: $CM_KEY_ALIAS
        key_password: $CM_KEY_PASSWORD
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Decode and set up keystore
        script: echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.jks
        
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true
